name: Bug report
description: Help us improve HPLOP by reporting a bug.
labels: [bug]

body:
- type: markdown
  attributes:
    value: "## Welcome!"

- type: input
  attributes:
    label: "Python version:"
    placeholder: "Ex: 3.8"
