name: Documentation
description: Report an issue related to the HPLOP documentation.
title: ""
labels: [documentation]

body:
- type: textarea
  attributes: 
    label: "Issue with current documentation:"
    description: >
      Please make sure to leave a reference to the document/code you're
      referring to.

- type: textarea
  attributes:
    label: "Idea or request for content:"
    description: >
      Please describe as clearly as possible what topics you think are missing
      from the current documentation.

- type: textarea
  attributes:
    label: "Additional context:"
    description: >
      Here you can provide any unmentioned details that you consider relevant.
