name: Documentation
description: Help us improve HPLOP's documentation by reporting an issue.
title: "DOC: <Please, write a comprehensive title after the 'DOC:' prefix>"
labels: [documentation]

body:
- type: textarea
  attributes: 
    label: "Issue with current documentation:"
    description: >
      Please make sure to leave a reference to the document/code you're
      referring to.

- type: textarea
  attributes:
    label: "Idea or request for content:"
    description: >
      Please describe as clearly as possible what topics you think are missing
      from the current documentation.

- type: textarea
  attributes:
    label: "Additional context:"
    description: >
      Here you can provide any unmentioned details that you consider relevant.

- type: checkboxes
  attributes:
    label: Would you like to fix it?
    description: >
      If you want to try to solve this issue by yourself, check the following checkbox. 
      A maintainer will assign you the task to let others know that someone is already working on it.
    options:
      - label: I want to give it a try.
  validations:
    required: false
      
